### ISSUE TITLE
Split `invalid/float/trailing-us-exp.toml` into two tests

### ISSUE THREAD

**Issue by gnarlyquack** [toml-lang/toml-test#139]
With two invalid cases combined, parsers that detect one but not the other will still pass the overall test.

**Comment by arp242** [comment]
Your PR #138 fixed this (there's already a `exp-leading-us` test, so no need to do anything else).

**Comment by gnarlyquack** [comment]
PR #138 changed `exp-trailing-us.toml`, which tests:
```
exp-trailing-us = 1e23_
```

`trailing-us-exp.toml` tests:
```
trailing-us-exp = 1_e2
trailing-us-exp2 = 1.2_e2
```

Each test has an invalid underscore in different positions of the float. Assuming we want to test against all these scenarios, it seems to me that the tests in `trailing-us-exp.toml` should be split out.

Normally I'd just submit a PR, but I think that adding/removing tests may require some changes in the binary in addition to just changing the tests, and I don't know the first thing about Go.

**Comment by arp242** [comment]
> adding/removing tests may require some changes in the binary in addition to just changing the tests, and I don't know the first thing about Go.

The entire directory is included; you don't need to do anything to add or remove a test other than create a file.

**Comment by arp242** [comment]
Fixed in https://github.com/toml-lang/toml-test/commit/55be8217b690494533f13976273aabefe2a34a3b

**Comment by gnarlyquack** [comment]
Thank you! I'll keep that in mind if I have future PRs.

Do the `tests\files-toml-x` files need to be updated?
