### ISSUE TITLE
[Valid Tests] Add Extra Spaces in Inline Tables

### ISSUE THREAD

**Issue by wyatt-herkamp** [toml-lang/toml-test#146]
So I was using [smol-toml](https://github.com/squirrelchat/smol-toml)

And I found an issue where toml inline like
```toml
clap = { version = "4"  , features = ["derive", "cargo"] }
```
Would not not parse. We solved the issue in https://github.com/squirrelchat/smol-toml/pull/8

However, the developer suggested that these cases get added to the toml-test

So basically toml-test needs to have a test for extra spaces inside the inline tables as they are valid toml just not properly formatted.

**Comment by arp242** [comment]
Added some tests for this; thanks!
