### ISSUE TITLE
Inconsistent test result of '+inf'

### ISSUE THREAD

**Issue by Bowen7** [toml-lang/toml-test#150]
The `+inf` returns
``` json
{
    "type": "float",
    "value": "inf"
}
```
in the `valid/spec/float-2.json` file
https://github.com/toml-lang/toml-test/blob/8bdabb239e349833ee60c793cd720c44b1fc5b8f/tests/valid/spec/float-2.toml#L3

https://github.com/toml-lang/toml-test/blob/8bdabb239e349833ee60c793cd720c44b1fc5b8f/tests/valid/spec/float-2.json#L6-L9

However, it returns
``` diff
{
    "type": "float",
-    "value": "inf"
+    "value": "+inf"
}
```
in the `valid/float/inf-and-nan.json` file

https://github.com/toml-lang/toml-test/blob/8bdabb239e349833ee60c793cd720c44b1fc5b8f/tests/valid/float/inf-and-nan.toml#L8

https://github.com/toml-lang/toml-test/blob/8bdabb239e349833ee60c793cd720c44b1fc5b8f/tests/valid/float/inf-and-nan.json#L10-L13

**Comment by arp242** [comment]
Is this causing practical issues for you?

**Comment by Bowen7** [comment]
I just wrote a parser for TOML for fun and found that it cannot pass these test suites.

**Comment by arp242** [comment]
That's actually a different issue @glguy, with the "I" in "Inf" being capitalized sometimes. That was fixed last year. I'm not 100% sure if that's in the latest tagged release (need to look that up), but it's definitely in the latest master.

Verified with:

    % git log -n1 
    commit 4bcf07d (HEAD -> main, tag: toml-parser-2.0.0.0, origin/main, origin/HEAD)
    Author: Eric Mertens <emertens@gmail.com>
    Date:   Sat Feb 24 08:27:42 2024 -0800
    
        Use NonEmpty in lexer context stack

    % git diff
    diff --git i/test-drivers/encoder/Main.hs w/test-drivers/encoder/Main.hs
    index 73998b2..e322d23 100644
    --- i/test-drivers/encoder/Main.hs
    +++ w/test-drivers/encoder/Main.hs
    @@ -56,6 +56,6 @@ decodeValue "date-local"     (lexValue -> Right (TokLocalDate      x)) = pure (T
     decodeValue "float"          (lexValue -> Right (TokFloat          x)) = pure (Toml.Double    x)
     decodeValue "float"          (lexValue -> Right (TokInteger        x)) = pure (Toml.Double    (fromInteger x))
     -- extra infinities as toml-tests are inconsistent
    -decodeValue "float"          "+Inf"                                    = pure (Toml.Double    (1/0))
    -decodeValue "float"          "-Inf"                                    = pure (Toml.Double    (-1/0))
    +-- decodeValue "float"          "+Inf"                                    = pure (Toml.Double    (1/0))
    +-- decodeValue "float"          "-Inf"                                    = pure (Toml.Double    (-1/0))
     decodeValue _                _                                         = empty
    diff --git i/toml-parser.cabal w/toml-parser.cabal
    index 9faf2c0..eb1ca76 100644
    --- i/toml-parser.cabal
    +++ w/toml-parser.cabal
    @@ -134,7 +134,7 @@ test-suite readme
             markdown-unlit:markdown-unlit ^>= {0.5.1, 0.6.0},
    
    % toml-test ./TomlDecoder
    toml-test v2023-12-07 [./TomlDecoder]: using embedded tests
      valid tests: 179 passed,  0 failed
    invalid tests: 368 passed,  0 failed
    
    % toml-test -encoder ./TomlEncoder
    toml-test v2023-12-07 [./TomlEncoder]: using embedded tests
    encoder tests: 179 passed,  0 failed

(I made sure to rebuild the TomlDecoder/TomlEncoder with the changes).
