### ISSUE TITLE
Invalid JSON in example code

### ISSUE THREAD

**Issue by Bagolly** [toml-lang/toml-test#158]
The first three example JSON files under the section [JSON encoding](https://github.com/toml-lang/toml-test?tab=readme-ov-file#json-encoding) seem to be invalid.

All examples (apart from line 2 in example 3) use `:` as the separator between their key/value pairs instead of `,`, while the third example also changed the value of the array's first element from `"a"` to `"1"`.

**Comment by arp242** [comment]
Yeah, not sure how that happened 😅 Been broken for close to 3 years too (since 1ba64eb).

**Comment by Bagolly** [comment]
Hey, seems like the last issue is still there; the first value in the JSON array (example 3) should be `"a"`, not `"1"`.
