### ISSUE TITLE
Should leap seconds be validated?

### ISSUE THREAD

**Issue by Bagolly** [toml-lang/toml-test#160]
While testing my TOML parser against the awesome test suite here, I came accross an edge case that I didn't see much information about.

TOML uses timestamps "_as defined in RFC 3339_" , and the rule for seconds is: 
```abnf
time-second = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second rules
```
Looking up "leap second rules", according to RFC3339, [Appendix D](https://datatracker.ietf.org/doc/html/rfc3339#appendix-D)
>When required, insertion of a leap second occurs as an extra second
   at the end of a day in UTC, represented by a timestamp of the form
   YYYY-MM-DDT23:59:60Z 

My question is, should parsers validate TOML timestamps with leap seconds against the above pattern?
The only relevant test I could find was in  `invalid/datetime/second-over.toml`, but that test just checks for an out of range second, not a leap second.

 At first glance:
Pros:
- Correctness, but since this is a somewhat obscure feature, even that may be questionable.
- Conformance to the TOML ABNF.

Cons:
- Would break several, if not most existing implementations, which is a lot of trouble for something that will be [obsoleted](https://en.wikipedia.org/wiki/Leap_second#:~:text=After%20many%20years%20of%20discussions,second%20by%20or%20before%202035.) by 2035 at the latest.
- Extra validation code required in the parser

As it stands, there are valid RFC3339 timestamps that are not accepted by TOML parsers, and invalid timestamps that are.

With that said, I'd appreciate some advice from other implementors; should an implementation:
- Validate leap seconds as the ABNF requires?
- Normalize leap seconds? (like setting back to 59 in the case of 60)
- Report leap seconds as an error?
- Other?

**Comment by arp242** [comment]
I added some tests for datetime boundary conditions some time ago, and intentionally left leap seconds out of it. I think it's too uncommon of a case to worry about in TOML. If you want to support it: fine. If you don't: also fine. I suspect literally no one is ever has or is going to run in to trouble here, so any effort that goes in to this strikes me as wasted effort.

We can reconsider if someone has a real practical problem or issue, rather than an abstract/theoretical one.

**Comment by BurntSushi** [comment]
> Normalize leap seconds? (like setting back to 59 in the case of 60)

This is what [Temporal](https://tc39.es/proposal-temporal/docs/zoneddatetime.html) does:

> NOTE: Although Temporal does not deal with leap seconds, dates coming from other software may have a second value of 60. In the default 'constrain' mode and when parsing an ISO 8601 string, this will be converted to 59. In 'reject' mode, this function will throw, so if you have to interoperate with times that may contain leap seconds, don't use reject.

And [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545) contains a relevant recommendation:

> Implementations that do not support leap seconds SHOULD interpret the second 60 as equivalent to the second 59.
