### ISSUE TITLE
Any plan for man page or other stand along documentation?

### ISSUE THREAD

**Issue by Hellseher** [toml-lang/toml-test#163]
Hi,

While preparing this project for Guix's package index I missed any man page or
other documentation source which may be packed together with it. Even the `-h`
looks fantastic it would be a nice touch to hav man/info file as well (something
like in https://github.com/mrtazz/checkmake).

Open this issue as a feature request rather than a bug report.

Thanks,
Oleg

**Comment by Hellseher** [comment]
Thanks for your replay.

Just some words of compliment, comparing to other Golang projects I've reviewed,
your's has got quite a well written (and at least has one!) README, appropriate
versioning, enabled CI and active development work.

It's included in Guix index after request of interested user.
- https://issues.guix.gnu.org/72874
- https://packages.guix.gnu.org/packages/toml-test/

Thanks,
Oleg

**Comment by arp242** [comment]
Thank you :-)

I did a bit of work to automatically convert a "human readable usage text" to a manpage in my [elles](https://github.com/arp242/elles) tool a while ago (in the `zli2` directory); it has a `-manpage` flag to print a manpage.

It doesn't quite work well and has a few rough edges, and I don't really haven't really had the time (or interest, to be honest) to fix it, but I do plan to fix it ... eventually.
